default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>
  <% if ENV['DATABASE_URL'] %>
  url: <%= ENV['DATABASE_URL'] %>
  <% end %>
  <% if ENV['DATABASE_USERNAME'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  <% end %>
  <% if ENV['DATABASE_PASSWORD'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  <% end %>

development:
  <<: *default
  database: <%= ENV['DATABASE'] || 'sonarxx' %>

test:
  <<: *default
  database: <%= ENV['DATABASE_TEST'] || 'sonarxx' %>

production:
  <<: *default

#   : 1726309265:0;sudo apt-get install libpq-dev
# : 1726309297:0;sudo yum install postgresql-devel\